# -*- coding: utf-8 -*-
"""Retreiving company fundamentals with python to Excel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l_Wd2BPLXhSqxk1NKswke0KBo6D1X_DD
"""

import requests
import pandas as pd
pd.options.display.float_format='{:,.2f}'.format
company='AAPL'
IS=requests.get(f'https://financialmodelingprep.com/api/v3/income-statement/{company}?limit=120&apikey=5440fa1b83055823728a35b8988f31eb').json()
BS=requests.get(f'https://financialmodelingprep.com/api/v3/balance-sheet-statement/{company}?limit=120&apikey=5440fa1b83055823728a35b8988f31eb').json()
CF=requests.get(f'https://financialmodelingprep.com/api/v3/cash-flow-statement/{company}?limit=120&apikey=5440fa1b83055823728a35b8988f31eb').json()
Ratios=requests.get(f'https://financialmodelingprep.com/api/v3/ratios/{company}?limit=120&apikey=5440fa1b83055823728a35b8988f31eb').json()
Key_matrix=requests.get(f'https://financialmodelingprep.com/api/v3/key-metrics/{company}?limit=120&apikey=5440fa1b83055823728a35b8988f31eb').json()
profile=requests.get(f'https://financialmodelingprep.com/api/v3/profile/{company}?limit=120&apikey=5440fa1b83055823728a35b8988f31eb').json()

Ratios

millions=1000000
financials={}
dates=[2021,2020,2019,2018,2017]
for item in range(5):
  financials[dates[item]]={}
  # Key mtrics
  financials[dates[item]]['mktcap']=Key_matrix[item]['marketCap'] /millions
  financials[dates[item]]['Debt to equity']=Key_matrix[item]['debtToEquity']
  financials[dates[item]]['Debt to Assets']=Key_matrix[item]['debtToAssets']
  financials[dates[item]]['Revenue per share']=Key_matrix[item]['revenuePerShare']
  financials[dates[item]]['NI per share']=Key_matrix[item]['netIncomePerShare']

  financials[dates[item]]['revenue']=IS[item]['revenue']/millions
  financials[dates[item]]['Gross profit']=IS[item]['grossProfit']/millions
  financials[dates[item]]['R&D expense']=IS[item]['researchAndDevelopmentExpenses']/millions
  financials[dates[item]]['Op expenses']=IS[item]['operatingExpenses']/millions
  financials[dates[item]]['Op Income']=IS[item]['operatingIncome']/millions
  financials[dates[item]]['Net Income']=IS[item]['netIncome']/millions

  financials[dates[item]]['Cash']=BS[item]['cashAndCashEquivalents']/millions
  financials[dates[item]]['Inventory']=BS[item]['cashAndCashEquivalents']/millions
  financials[dates[item]]['Cur Assets']=BS[item]['totalCurrentAssets']/millions
  financials[dates[item]]['LT Assets']=BS[item]['totalNonCurrentAssets']/millions
  financials[dates[item]]['Int Assets']=BS[item]['intangibleAssets']/millions
  financials[dates[item]]['Total Assets']=BS[item]['totalAssets']/millions
  financials[dates[item]]['Cur Liab']=BS[item]['totalCurrentLiabilities']/millions
  financials[dates[item]]['LT Debt']=BS[item]['longTermDebt']/millions
  financials[dates[item]]['LT Liab']=BS[item]['totalNonCurrentLiabilities']/millions
  financials[dates[item]]['Total Liab']=BS[item]['totalLiabilities']/millions
  financials[dates[item]]['SH Equity']=BS[item]['totalStockholdersEquity']/millions
  
  financials[dates[item]]['CF Operations']=CF[item]['operatingCashFlow']/millions
  financials[dates[item]]['CF Investing']=CF[item]['netCashUsedForInvestingActivites']/millions
  financials[dates[item]]['CF Financing']=CF[item]['netCashUsedProvidedByFinancingActivities']/millions
  financials[dates[item]]['CAPEX']=CF[item]['capitalExpenditure']/millions
  financials[dates[item]]['FCF']=CF[item]['freeCashFlow']/millions
  financials[dates[item]]['Dividends Paid']=CF[item]['dividendsPaid']/millions
  # income statement Ratio
  financials[dates[item]]['Gross Profit Margin']=Ratios[item]['grossProfitMargin']
  financials[dates[item]]['OP Margin']=Ratios[item]['operatingProfitMargin']
  financials[dates[item]]['Int Coverage']=Ratios[item]['capitalExpenditureCoverageRatio']
  financials[dates[item]]['Net Profit Margin']=Ratios[item]['netProfitMargin']
  financials[dates[item]]['Dividend Yield']=Ratios[item]['dividendYield']
  # BS ratios
  financials[dates[item]]['Current Ratio']=Ratios[item]['currentRatio']
  financials[dates[item]]['Operating Cycle']=Ratios[item]['operatingCycle']
  financials[dates[item]]['Days Of Ap Outstanding']=Ratios[item]['daysOfPayablesOutstanding']
  financials[dates[item]]['Cash Conversion Cycle']=Ratios[item]['cashConversionCycle']
  # Return Ratios
  financials[dates[item]]['ROA']=Ratios[item]['returnOnAssets']
  financials[dates[item]]['ROE']=Ratios[item]['returnOnEquity']
  financials[dates[item]]['ROCE']=Ratios[item]['returnOnCapitalEmployed']
  financials[dates[item]]['Dividend Yield']=Ratios[item]['dividendYield']
  # Price Ratios
  financials[dates[item]]['PE']=Ratios[item]['priceEarningsRatio']
  financials[dates[item]]['PS']=Ratios[item]['priceToSalesRatio']
  financials[dates[item]]['PB']=Ratios[item]['priceToBookRatio']
  financials[dates[item]]['Price To FCF']=Ratios[item]['priceToFreeCashFlowsRatio']
  financials[dates[item]]['PEG']=Ratios[item]['priceEarningsToGrowthRatio']

fundamentals=pd.DataFrame.from_dict(financials,orient='columns')
fundamentals['GAGR']=(fundamentals[2021]/fundamentals[2017])**(1/5)-1
fundamentals['2021 Growth']=(fundamentals[2021]-fundamentals[2020])/fundamentals[2020]
fundamentals['2020 Growth']=(fundamentals[2020]-fundamentals[2019])/fundamentals[2019]
fundamentals['2019 Growth']=(fundamentals[2019]-fundamentals[2018])/fundamentals[2018]  
fundamentals['2018 Growth']=(fundamentals[2018]-fundamentals[2017])/fundamentals[2017]
fundamentals.to_excel('fundamentals.xlsx')
fundamentals